### ISSUE TITLE
Error message when renaming a node on the diagram

### ISSUE THREAD

**Issue by koegel** [eclipsesource/coffee-editor#187]
[GLSP-Server] Could not process message:ActionMessage [action=identifiableRequestAction, clientId=workflow-diagram-notation_5_widget]

**Comment by koegel** [comment]
EXPLORER
No callers have been detected.
Palette
Nodes
Automated Task
Manual Task
Decision Node
Merge Node
Edges
Weighted Edge
Edge
A
Preheat
A
Brew
M
Refill water
M
Drink
M
Push
M
Check drip tray
A
dd
A
Water Ok
M
fdsafdsafsdaffffffffffffffffffffffffffffffffffffffff
A
undefined
A
undefined
M
dsa
A
adsa
A
Preheat
A
Brew
M
Refill water
M
Drink
M
Push
M
Check drip tray
A
Check Water
A
Water Ok
M
fdsafdsafsdaffffffffffffffffffffffffffffffffffffffff
A
Preheat
A
Brew
M
Refill water
M
Drink
M
Push
M
Check drip tray
A
Check Water
A
Water Ok
M
fdsafdsafsdaffffffffffffffffffffffffffffffffffffffff
A
Preheat
A
Brew
M
Refill water
M
Drink
M
Push
M
Check drip tray
A
Check Water
A
Water Ok
M
fdsafdsafsdaffffffffffffffffffffffffffffffffffffffff
A
undefined
A
undefined
A
Preheat
A
Brew
M
Refill water
M
Drink
M
Push
M
Check drip tray
A
Check Water
A
Water Ok
M
fdsafdsafsdaffffffffffffffffffffffffffffffffffffffff
A
undefined
A
undefined
A
Preheat
A
Brew
M
Refill water
M
Drink
M
Push
M
Check drip tray
A
Check Water
A
Water Ok
M
fdsafdsafsdaffffffffffffffffffffffffffffffffffffffff
A
undefined
A
undefined
A
Preheat
A
Brew
M
Refill water
M
Drink
M
Push
M
Check drip tray
A
dd
A
Water Ok
M
fdsafdsafsdaffffffffffffffffffffffffffffffffffffffff
A
undefined
A
undefined
M
fdsadsada
A
adsa
A
Preheat
A
Brew
M
Refill water
M
Drink
M
Push
M
Check drip tray
A
dd
A
Water Ok
M
fdsafdsafsdaffffffffffffffffffffffffffffffffffffffff
A
undefined
A
undefined
M
fdsadsada
A
adsa
A
Preheat
A
Brew
M
Refill water
M
Drink
M
Push
M
Check drip tray
A
dd
A
Water Ok
M
fdsafdsafsdaffffffffffffffffffffffffffffffffffffffff
A
undefined
A
undefined
M
dsa
A
adsa
[GLSP-Server] Could not process message:ActionMessage [action=identifiableRequestAction, clientId=workflow-diagram-notation_7_widget]
java.lang.NullPointerException at com.eclipsesource.glsp.example.workflow.labeledit.WorkflowLabelEditValidator.lambda$validate$1(WorkflowLabelEditValidator.java:23) at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) at java.base/java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1624) at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528) at com.eclipsesource.glsp.example.workflow.labeledit.WorkflowLabelEditValidator.validate(WorkflowLabelEditValidator.java:23) at com.eclipsesource.glsp.server.actionhandler.ValidateLabelEditActionHandler.execute(ValidateLabelEditActionHandler.java:45) at com.eclipsesource.glsp.server.actionhandler.AbstractActionHandler.execute(AbstractActionHandler.java:43) at com.eclipsesource.glsp.server.actionhandler.DIActionProcessor.dispatch(DIActionProcessor.java:41) at com.eclipsesource.glsp.api.action.ActionProcessor.process(ActionProcessor.java:42) at com.eclipsesource.glsp.api.action.ActionProcessor.process(ActionProcessor.java:58) at com.eclipsesource.glsp.server.jsonrpc.DefaultGLSPServer.process(DefaultGLSPServer.java:94) at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65) at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152) at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220) at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187) at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194) at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94) at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:834)
Cancel
OK
