### ISSUE TITLE
Intermittent error on adding elements in the tree

### ISSUE THREAD

**Issue by planger** [eclipsesource/coffee-editor#206]
It looks like this error doesn't appear every time when adding elements, but sometimes at least. Maybe the stacktrace is sufficient to find out what's going on.
```
com.eclipsesource.modelserver.common.codecs.DecodingException: org.eclipse.emf.ecore.resource.Resource$IOWrappedException: Package with uri 'http://www.eclipsesource.com/schema/2019/modelserver/command' not found. (file:///home/philip/Git/OpenSource/coffee-editor/web/browser-app/virtual.xmi, 2, 369) java.lang.RuntimeException: com.eclipsesource.modelserver.common.codecs.DecodingException: org.eclipse.emf.ecore.resource.Resource$IOWrappedException: Package with uri 'http://www.eclipsesource.com/schema/2019/modelserver/command' not found. (file:///home/philip/Git/OpenSource/coffee-editor/web/browser-app/virtual.xmi, 2, 369) at com.eclipsesource.modelserver.client.XmiToEObjectSubscriptionListener.decode(XmiToEObjectSubscriptionListener.java:46) at java.base/java.util.Optional.flatMap(Optional.java:294) at com.eclipsesource.modelserver.client.TypedSubscriptionListener.onNotification(TypedSubscriptionListener.java:48) at com.eclipsesource.modelserver.client.ModelServerClient$1.onMessage(ModelServerClient.java:335) at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:290) at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:220) at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:100) at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:247) at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:181) at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:834) Caused by: com.eclipsesource.modelserver.common.codecs.DecodingException: org.eclipse.emf.ecore.resource.Resource$IOWrappedException: Package with uri 'http://www.eclipsesource.com/schema/2019/modelserver/command' not found. (file:///home/philip/Git/OpenSource/coffee-editor/web/browser-app/virtual.xmi, 2, 369) at com.eclipsesource.modelserver.common.codecs.XmiCodec.decode(XmiCodec.java:86) at com.eclipsesource.modelserver.common.codecs.XmiCodec.decode(XmiCodec.java:56) at com.eclipsesource.modelserver.client.XmiToEObjectSubscriptionListener.decode(XmiToEObjectSubscriptionListener.java:44) ... 12 more Caused by: org.eclipse.emf.ecore.resource.Resource$IOWrappedException: Package with uri 'http://www.eclipsesource.com/schema/2019/modelserver/command' not found. (file:///home/philip/Git/OpenSource/coffee-editor/web/browser-app/virtual.xmi, 2, 369) at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.handleErrors(XMLLoadImpl.java:77) at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:185) at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doLoad(XMLResourceImpl.java:261) at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563) at com.eclipsesource.modelserver.common.codecs.XmiCodec.decode(XmiCodec.java:84) ... 14 more Caused by: org.eclipse.emf.ecore.xmi.PackageNotFoundException: Package with uri 'http://www.eclipsesource.com/schema/2019/modelserver/command' not found. (file:///home/philip/Git/OpenSource/coffee-editor/web/browser-app/virtual.xmi, 2, 369) at org.eclipse.emf.ecore.xmi.impl.XMLHandler.getPackageForURI(XMLHandler.java:2643) at org.eclipse.emf.ecore.xmi.impl.XMLHandler.getFactoryForPrefix(XMLHandler.java:2476) at org.eclipse.emf.ecore.xmi.impl.XMLHandler.createObjectByType(XMLHandler.java:1353) at org.eclipse.emf.ecore.xmi.impl.XMLHandler.createTopObject(XMLHandler.java:1522) at org.eclipse.emf.ecore.xmi.impl.XMLHandler.processElement(XMLHandler.java:1044) at org.eclipse.emf.ecore.xmi.impl.XMIHandler.processElement(XMIHandler.java:78) at org.eclipse.emf.ecore.xmi.impl.XMLHandler.startElement(XMLHandler.java:1026) at org.eclipse.emf.ecore.xmi.impl.XMLHandler.startElement(XMLHandler.java:720) at org.eclipse.emf.ecore.xmi.impl.XMIHandler.startElement(XMIHandler.java:190) at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510) at java.xml/com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:731) at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1397) at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$ContentDriver.scanRootElementHook(XMLDocumentScannerImpl.java:1292) at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3063) at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:836) at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605) at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534) at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888) at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824) at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216) at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635) at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324) at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:175) ... 17 more 
```

**Comment by eneufeld** [comment]
Didn't encounter this since the updates. Please feel free to reopen if this happens again.
